- name: Install MySQL repository
  yum:
    name: "https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Install MySQL packages
  yum:
    name: mysql-server #"{{ item }}"
    state: present
    #with_items:
    #- mysql-server
    #- MySQL-python
- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: Make sure mysqld service is running
  service:
    name: mysqld
    state: started
    enabled: True

- name: Create database user with with all database privileges
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pw }}"
    priv: '*.*:ALL'
    state: present

- name: Create DB
  mysql_db:
    check_implicit_admin: yes
    login_user: "{{ db_user }}"
    login_password: "{{ db_pw }}"
    name: "{{ db_name }}"
    state: present
