- name: Deploy VPC
  ec2_vpc_net:
    name: Base
    state: present
    cidr_block: 10.0.0.0/16
    region: "{{ region }}"
  register: vpc

- name: Deploy Public subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.255.192/28
    tags:
      Name: Public Subnet
  register: public_subnet      

- name: Deploy Private subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{vpc.vpc.id }}"
    cidr: 10.0.255.208/28 
    tags:
      Name: Private Subnet
  register: private_subnet

- name: Deploy Data subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.255.224/28
    tags:
      Name: Data Subnet
  register: data_subnet
